Fix Rust formatting when //:format is called in different subdirectory
We have been seening problems when the Rust formatter is called
from a subdirectory and not the workspace root directory.

The root cause is that rustfmt appears to look for the file list
based on the BUILD_WORKING_DIRECTORY instead of
BUILD_WORKSPACE_DIRECTORY or the current working directory of format.sh

This patch fixes the issue by unsetting the BUILD_WORKING_DIRECTORY
if format.sh has BUILD_WORKSAPCE_DIRECTORY is set.

This has been locally tested:

before:
Running in a subdirectory

```
> bazel run //:format
INFO: Invocation ID: c0ef6738-6805-4ee3-8d5a-ab5a7c393865
INFO: Analyzed target //:format (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //tools:format up-to-date:
  bazel-bin/tools/format.bash
INFO: Elapsed time: 0.351s, Critical Path: 0.03s
INFO: 2 processes: 2 internal.
INFO: Build completed successfully, 2 total actions
INFO: Running command line: bazel-bin/tools/format.bash
684 files left unchanged
Formatted Python in 0m0.016s
Formatted Starlark in 0m0.066s
Formatted Jsonnet in 0m0.144s
Formatted Go in 0m0.067s
Formatted Shell in 0m0.004s
Formatted Protocol Buffer in 0m0.978s
Formatted C++ in 0m0.010s
Formatted YAML in 0m0.019s
Error: file `a/lib.rs` does not exist
Formatted Rust in 0m0.020s
FAILED: A formatter tool exited with code 123
```

after:

```
> bazel run //:format
INFO: Invocation ID: 0b2f4cff-24af-474a-aa25-1a32d0ce74a9
INFO: Analyzed target //:format (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //tools:format up-to-date:
  bazel-bin/tools/format.bash
INFO: Elapsed time: 0.380s, Critical Path: 0.03s
INFO: 2 processes: 2 internal.
INFO: Build completed successfully, 2 total actions
INFO: Running command line: bazel-bin/tools/format.bash
684 files left unchanged
Formatted Python in 0m0.017s
Formatted Starlark in 0m0.066s
Formatted Jsonnet in 0m0.146s
Formatted Go in 0m0.065s
Formatted Shell in 0m0.004s
Formatted Protocol Buffer in 0m0.970s
Formatted C++ in 0m0.010s
Formatted YAML in 0m0.019s
Formatted Rust in 0m0.401s
```