fix undocumented dependency on aspect_bazel_lib for WORKSPACE users
I noticed that the instructions in each release for using aspect-build/rules_lint with WORKSPACE don't include the dependency that it has on aspect-build/bazel-lib, and so if you follow the setup instructions literally you'll end up with errors when `bazel run`-ing your formatter target:

```
$ bazel run //tools:format
ERROR: Skipping '//tools:format': error loading package 'tools': at /private/var/tmp/_bazel_mattbrown/d7cfcf96ac70d7089c913ecc8b613cd1/external/aspect_rules_lint/format/defs.bzl:33:6: at /private/var/tmp/_bazel_mattbrown/d7cfcf96ac70d7089c913ecc8b613cd1/external/aspect_rules_lint/format/private/formatter_binary.bzl:3:6: Unable to find package for @@aspect_bazel_lib//lib:paths.bzl: The repository '@@aspect_bazel_lib' could not be resolved: Repository '@@aspect_bazel_lib' is not defined.
```

I suppose ideally this library would export a deps.bzl file following the usual convention, so that setting up rules_lint in a project requires less to copy and paste; happy to change this PR to do that if desired.